# This is a config for Novita Agent Sandbox template.
# You can use template ID (w6e9tkugl2ifym9p09bb) to create a sandbox:

# Python SDK
# from novita_sandbox.core import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("w6e9tkugl2ifym9p09bb") # Sync sandbox
# sandbox = await AsyncSandbox.create("w6e9tkugl2ifym9p09bb") # Async sandbox

# JS SDK
# import { Sandbox } from 'novita-sandbox'
# const sandbox = await Sandbox.create('w6e9tkugl2ifym9p09bb')

memory_mb = 2_048
cpu_count = 2
start_cmd = "node ./scripts/server.js"
dockerfile = "novita.Dockerfile"
template_id = "w6e9tkugl2ifym9p09bb"
